-- Migration: create custom_contacts table

CREATE TABLE public.custom_contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  interested_division TEXT,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE public.custom_contacts ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.custom_contacts IS 'Stores contact form submissions from the website.';
COMMENT ON COLUMN public.custom_contacts.full_name IS 'User''s full name.';
COMMENT ON COLUMN public.custom_contacts.email IS 'User''s email address.';
COMMENT ON COLUMN public.custom_contacts.interested_division IS 'The division the user is interested in.';
COMMENT ON COLUMN public.custom_contacts.message IS 'The message content from the user.';

CREATE POLICY "Allow anonymous inserts"
ON public.custom_contacts
FOR INSERT
WITH CHECK (true);
