-- 003-create-media.sql

-- 1. Create media_packages
CREATE TABLE IF NOT EXISTS public.media_packages (
    id bigint PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    name text NOT NULL,
    description text,
    thumbnail text,
    category text,
    standard_price integer NOT NULL DEFAULT 0,
    premium_price integer NOT NULL DEFAULT 0,
    included_services text[],
    is_active boolean NOT NULL DEFAULT true
);

COMMENT ON TABLE public.media_packages IS 'Stores the pre-defined media packages like Content Engine, Visual Impact, etc.';

-- 2. Create media_services
CREATE TABLE IF NOT EXISTS public.media_services (
    id bigint PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    key text NOT NULL UNIQUE,
    label text NOT NULL,
    description text,
    price_min integer NOT NULL DEFAULT 0,
    category text,
    is_active boolean NOT NULL DEFAULT true
);

COMMENT ON TABLE public.media_services IS 'Stores individual a la carte services for the "Build Your Own Package" customizer.';

-- 3. Create media_quotes
CREATE TABLE IF NOT EXISTS public.media_quotes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    name text NOT NULL,
    email text NOT NULL,
    phone text,
    details text,
    status text NOT NULL DEFAULT 'new'
);

COMMENT ON TABLE public.media_quotes IS 'Collects inquiries from the "Get a Custom Quote" form.';

-- 4. Create media_bookings
CREATE TABLE IF NOT EXISTS public.media_bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    package_id bigint REFERENCES public.media_packages(id),
    total_price integer NOT NULL,
    client_details jsonb,
    package_details jsonb,
    status text NOT NULL DEFAULT 'pending_confirmation'
);

COMMENT ON TABLE public.media_bookings IS 'Stores completed bookings from the checkout process.';
COMMENT ON COLUMN public.media_bookings.package_id IS 'FK to media_packages. Can be NULL if it is a custom quote.';
COMMENT ON COLUMN public.media_bookings.client_details IS 'Stores client info like name, email, phone, company_name.';
COMMENT ON COLUMN public.media_bookings.package_details IS 'Stores package info, like tier or list of custom services.';

-- 5. Insert mock packages
INSERT INTO public.media_packages (id, name, description, thumbnail, category, standard_price, premium_price, included_services, is_active)
VALUES
    (1, 'Content Engine', 'Your all-in-one solution for consistent, high-quality content creation, from writing to video timelines.', 'https://images.unsplash.com/photo-1516116462742-f411874254A6?w=600', 'Content Creation', 10000, 20000, '{"Content Writing", "Caption Generation", "Video Timeline"}'::text[], true),
    (2, 'Visual Impact Bundle', 'Elevate your brand''s visual appeal with professional thumbnail design, video editing, and storytelling assets.', 'https://images.unsplash.com/photo-1611162617213-7d724e0f2241?w=600', 'Visual Design', 15000, 28000, '{"Thumbnail Design", "Video Editing", "Video Storytelling Assets (caption + timeline)"}'::text[], true),
    (3, 'Audience Amplifier', 'Reach new heights with targeted social media marketing, ad campaigns, and powerful SEO optimization.', 'https://images.unsplash.com/photo-1611926653458-0929221b2712?w=600', 'Marketing', 25000, 50000, '{"Social Media Marketing", "Running Ads (Meta, Google)", "SEO Optimization"}'::text[], true),
    (4, 'Community Connect', 'Build a loyal following through strategic collaborations, brand tie-ups, and active community engagement.', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600', 'Community', 20000, 40000, '{"Collaborations", "Brand Tie-ups", "Community Engagement"}'::text[], true),
    (5, 'Growth Intelligence', 'Make data-driven decisions with in-depth performance analysis, SEO, and strategic content planning.', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600', 'Strategy', 25000, 50000, '{"Performance Analysis", "SEO Optimization", "Content Planning & Strategy"}'::text[], true),
    (6, 'Creator''s Choice', 'Don''t see a package that fits? Build your own by selecting only the services you need.', 'https://images.unsplash.com/photo-1553877522-c36980345885?w=600', 'Custom', 0, 0, '{"Fully customizable - client selects any combination of services"}'::text[], false)
ON CONFLICT (id) DO NOTHING;

-- 6. Insert mock services
INSERT INTO public.media_services (id, key, label, description, price_min, category, is_active)
VALUES
    (1, 'content_writing', 'Content Writing', 'Blog posts, articles, and scripts.', 8000, 'Content', true),
    (2, 'caption_generation', 'Caption Generation', 'Engaging captions for social media posts.', 5000, 'Content', true),
    (3, 'video_timeline', 'Video Timeline', 'Strategic planning and timeline creation for video content.', 6000, 'Content', true),
    (4, 'thumbnail_design', 'Thumbnail Design', 'Click-worthy thumbnails for YouTube and other platforms.', 7000, 'Visuals', true),
    (5, 'video_editing', 'Video Editing', 'Professional editing for short or long-form content.', 12000, 'Visuals', true),
    (6, 'video_storytelling', 'Video Storytelling Assets', 'Captions, timelines, and assets for compelling stories.', 7500, 'Visuals', true),
    (7, 'smm', 'Social Media Marketing', 'Managing and growing your social media presence.', 15000, 'Marketing', true),
    (8, 'ads', 'Running Ads (Meta, Google)', 'Full-service ad campaign management.', 20000, 'Marketing', true),
    (9, 'seo', 'SEO Optimization', 'Improve your search engine ranking.', 18000, 'Marketing', true),
    (10, 'collabs', 'Collaborations', 'Identifying and managing creator collaborations.', 10000, 'Community', true),
    (11, 'brand_tieups', 'Brand Tie-ups', 'Securing and managing brand sponsorship deals.', 15000, 'Community', true),
    (12, 'community_engagement', 'Community Engagement', 'Actively managing and engaging with your online community.', 9000, 'Community', true),
    (13, 'analysis', 'Performance Analysis', 'Monthly reports and insights on your content performance.', 12000, 'Strategy', true),
    (14, 'strategy', 'Content Planning & Strategy', 'Long-term content calendar and strategic planning.', 15000, 'Strategy', true)
ON CONFLICT (id) DO NOTHING;

-- 7. Storage bucket and policies are not applied here in SQL migration; they are usually configured via Supabase UI or CLI.

-- 8. Enable RLS
ALTER TABLE public.media_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_bookings ENABLE ROW LEVEL SECURITY;

-- 9. Policies
CREATE POLICY IF NOT EXISTS "Allow public read access for packages"
ON public.media_packages FOR SELECT
USING (true);

CREATE POLICY IF NOT EXISTS "Allow public read access for services"
ON public.media_services FOR SELECT
USING (true);

CREATE POLICY IF NOT EXISTS "Allow anonymous inserts for quotes"
ON public.media_quotes FOR INSERT
WITH CHECK (true);

CREATE POLICY IF NOT EXISTS "Allow authenticated inserts for bookings"
ON public.media_bookings FOR INSERT
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY IF NOT EXISTS "Allow individual read access for bookings"
ON public.media_bookings FOR SELECT
USING (auth.uid() = user_id);
