// Focsera Terms of Use Page
// Framework: React + TypeScript (TSX)
// Usage: <TermsOfUsePage />
// Last Updated: 16 Nov 2025

import React from "react";

const TermsOfUsePage: React.FC = () => {
  return (
    <main className="min-h-screen bg-neutral-950 text-neutral-100">
      <section className="mx-auto max-w-5xl px-6 py-16">
        <h1 className="text-3xl font-bold tracking-tight mb-6">
          Focsera – Terms of Use
        </h1>

        <p className="text-sm text-neutral-400 mb-10">
          Last Updated: 16 November 2025
        </p>

        <div className="space-y-6 text-neutral-300 leading-relaxed">
          <p>
            This document is an electronic record in terms of the Information
            Technology Act, 2000 and rules made thereunder as applicable and the
            amended provisions pertaining to electronic records in various
            statutes as amended by the Information Technology Act, 2000. This
            electronic record is generated by a computer system and does not
            require any physical or digital signatures.
          </p>

          <p>
            This document is published in accordance with the provisions of Rule
            3 (1) of the Information Technology (Intermediaries Guidelines)
            Rules, 2011 that require publishing the rules and regulations,
            privacy policy and Terms of Use for access or usage of domain name{" "}
            <strong>https://www.focsera.in/</strong> (“Website”), including the
            related mobile site and mobile application (hereinafter referred to
            as the “Platform”).
          </p>

          <p>
            The Platform is owned by <strong>LAGISHETTY UDAY KUMAR</strong>, a
            company incorporated under the Companies Act, 1956 with its
            registered office at Gowthami Nagar Colony, Hyderabad, India
            (hereinafter referred to as “Platform Owner”, “we”, “us”, or
            “our”).
          </p>

          <p>
            Your use of the Platform and services and tools are governed by the
            following terms and conditions (“Terms of Use”) as applicable to the
            Platform including the applicable policies which are incorporated
            herein by way of reference. If you transact on the Platform, you
            shall be subject to the policies that are applicable to the Platform
            for such transaction.
          </p>

          <p>
            By mere use of the Platform, you shall be contracting with the
            Platform Owner and these Terms of Use including the policies
            constitute your binding obligations with the Platform Owner. These
            Terms of Use relate to your use of our website, goods (as applicable)
            or services (as applicable) (collectively, “Services”).
          </p>

          <p>
            Any terms and conditions proposed by you which are in addition to or
            which conflict with these Terms of Use are expressly rejected by the
            Platform Owner and shall be of no force or effect. These Terms of Use
            may be modified at any time without assigning any reason. It is your
            responsibility to periodically review these Terms of Use to stay
            informed of updates.
          </p>

          <p>
            For the purpose of these Terms of Use, wherever the context so
            requires, “you”, “your” or “user” shall mean any natural or legal
            person who has agreed to become a user or buyer on the Platform.
          </p>

          <p className="font-semibold uppercase">
            Accessing, browsing or otherwise using the platform indicates your
            agreement to all the terms and conditions under these terms of use,
            so please read them carefully before proceeding.
          </p>

          <p>
            To access and use the Services, you agree to provide true, accurate
            and complete information during and after registration, and you
            shall be responsible for all acts done through the use of your
            registered account on the Platform.
          </p>

          <p>
            Neither we nor any third parties provide any warranty or guarantee as
            to the accuracy, timeliness, performance, completeness or suitability
            of the information and materials offered on this website or through
            the Services for any specific purpose. You acknowledge that such
            information and materials may contain inaccuracies or errors and we
            expressly exclude liability for any such inaccuracies or errors to
            the fullest extent permitted by law.
          </p>

          <p>
            Your use of our Services and the Platform is solely and entirely at
            your own risk and discretion for which we shall not be liable to you
            in any manner. You are required to independently assess and ensure
            that the Services meet your requirements.
          </p>

          <p>
            The contents of the Platform and the Services are proprietary to us
            and licensed to us. You shall not have any authority to claim any
            intellectual property rights, title, or interest in its contents,
            including but not limited to design, layout, look, and graphics.
          </p>

          <p>
            You acknowledge that unauthorized use of the Platform and/or the
            Services may lead to action against you as per these Terms of Use
            and/or applicable laws.
          </p>

          <p>
            You agree to pay the charges associated with availing the Services.
          </p>

          <p>
            You agree not to use the Platform and/or Services for any purpose
            that is unlawful, illegal, or forbidden by these Terms or by Indian
            or local laws applicable to you.
          </p>

          <p>
            You acknowledge that the Platform and Services may contain links to
            third-party websites. On accessing these links, you will be governed
            by the terms and policies of such third-party websites. These links
            are provided solely for convenience.
          </p>

          <p>
            You understand that upon initiating a transaction for availing the
            Services, you are entering into a legally binding and enforceable
            contract with the Platform Owner.
          </p>

          <p>
            You shall indemnify and hold harmless the Platform Owner, its
            affiliates, officers, directors, agents, and employees from any
            claim, demand, penalty, or loss arising out of your breach of these
            Terms of Use, privacy policy, or applicable laws, including
            infringement of third-party rights.
          </p>

          <p>
            Notwithstanding anything contained herein, the parties shall not be
            liable for any failure or delay in performance due to force majeure
            events.
          </p>

          <p>
            These Terms shall be governed by and construed in accordance with
            the laws of India.
          </p>

          <p>
            All disputes arising out of or in connection with these Terms shall
            be subject to the exclusive jurisdiction of the courts in Hyderabad,
            Telangana.
          </p>

          <p>
            All concerns or communications relating to these Terms must be sent
            using the contact information provided on this website.
          </p>
        </div>
      </section>
    </main>
  );
};

export default TermsOfUsePage;
