// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Singleton pattern to prevent multiple instances during HMR
const createSupabaseClient = () => {
  return createClient<Database>(supabaseUrl, supabaseKey, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  });
};

// @ts-ignore
export const supabase = (window.supabase as ReturnType<typeof createClient<Database>>) || createSupabaseClient();

// @ts-ignore
if (!window.supabase) window.supabase = supabase;